### ISSUE TITLE
test task works locally but does not in jenkins instance

### ISSUE THREAD

**Issue by tzoratto** [sheehan/job-dsl-gradle-example#53]
Hi, 

I'm not sure if this issue is directly related to the gradle configuration from this repo or not so let me know if I'd better create it elsewhere.

**To reproduce the problem :** 

- create a job including the slackNotifier publisher (auto-generated DSL) : 

```
job ('test-slack') {
    publishers {
        slackNotifier {
            room('Dev Team A')
            notifyAborted(true)
            notifyFailure(true)
            notifyNotBuilt(true)
            notifyUnstable(true)
            notifyBackToNormal(true)
            notifySuccess(false)
            notifyRepeatedFailure(false)
            startNotification(false)
            includeTestSummary(false)
            includeCustomMessage(false)
            customMessage(null)
            buildServerUrl(null)
            sendAs(null)
            commitInfoChoice('NONE')
            teamDomain(null)
            authToken(null)
        }
    }
}
```

- add the slack plugin to the emulated Jenkins instance (in build.gradle)

`testPlugins 'org.jenkins-ci.plugins:slack:2.0.1'`

- set the Jenkins version to 2.16 or newer (in gradle.properties)

`jenkinsVersion=2.16`

At this point, if you run ./gradlew clean test on your local machine it should work.

Now, if you run the same "clean test" in the seed job on your Jenkins instance 

![sans titre](https://cloud.githubusercontent.com/assets/18479971/19409615/f82ced86-92d7-11e6-9687-d7de49244412.png)

it will eventually fail complaining about the missing slackNotifier method, exactly as if the slack plugin wasn't included in the emulated Jenkins instance ran during the test task. 

The process job DSL step works flawlessly though.

Everything works fine when you set the jenkins version in gradle.properties to 2.15 or older.

Notes :
- The exact same problem occurs with either a Jenkins instance version 2.9 or 2.23
- The exact same problem occurs regardless of the plugin (as soon as we are talking about auto-generated DSL)

**Comment by tzoratto** [comment]
Ok, I have a better grasp on the issue now. 

Extract from Jenkins 2.16 changeling :

> Fix plugin dependency resolution. Jenkins will now refuse to load plugins with unsatisfied dependencies, which resulted in difficult to diagnose problems. This may result in errors on startup if your instance has an invalid plugin configuration., check the Jenkins log for details. (issue 21486)

If I run the test task in debug mode : 

```
SEVERE: Failed Loading plugin Slack Notification Plugin v2.0.1 (slack)
20:42:31.966 [DEBUG] [TestEventLogger]     java.io.IOException: Slack Notification Plugin v2.0.1 failed to load.
20:42:31.967 [DEBUG] [TestEventLogger]      - JUnit Plugin v1.2-beta-4 is older than required. To fix, install v1.3 or later.
20:42:31.967 [DEBUG] [TestEventLogger]     	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
20:42:31.968 [DEBUG] [TestEventLogger]     	at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
20:42:31.968 [DEBUG] [TestEventLogger]     	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
20:42:31.969 [DEBUG] [TestEventLogger]     	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
20:42:31.969 [DEBUG] [TestEventLogger]     	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1038)
20:42:31.970 [DEBUG] [TestEventLogger]     	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
20:42:31.971 [DEBUG] [TestEventLogger]     	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
20:42:31.972 [DEBUG] [TestEventLogger]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
20:42:31.973 [DEBUG] [TestEventLogger]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
20:42:31.974 [DEBUG] [TestEventLogger]     	at java.lang.Thread.run(Thread.java:745)
```

That's why the test task doesn't work with Jenkins >= 2.16 with auto-generated DSL and plugins with unsatisfied dependencies. We have to add all dependencies by hand I reckon.
