### ISSUE TITLE
Test fails with multibranchPipelineJob

### ISSUE THREAD

**Issue by LawYard** [sheehan/job-dsl-gradle-example#78]
Hi!

I am using your code as a base for my dsl jobs repo.

Now I am trying to use Jenkins Pipeline and `gradlew clean test` fails when I add job with `multibranchPipelineJob` =(

**Fail log:**

```
14:19:18.939 [DEBUG] [TestEventLogger]     INFO: Prepared all plugins
14:19:19.067 [DEBUG] [TestEventLogger]     May 05, 2017 2:19:19 PM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
14:19:19.069 [DEBUG] [TestEventLogger]     WARNING: Failed to instantiate Key[type=com.cloudbees.hudson.plugins.folder.properties.FolderCredentialsProvider$FolderCredentialsProperty$DescriptorImpl, annotation=[none]]; skipping this component
14:19:19.071 [DEBUG] [TestEventLogger]     com.google.inject.ProvisionException: Unable to provision, see the following errors:
14:19:19.071 [DEBUG] [TestEventLogger] 
14:19:19.071 [DEBUG] [TestEventLogger]     1) Error injecting constructor, java.lang.NoClassDefFoundError: com/cloudbees/plugins/credentials/CredentialsProvider
14:19:19.071 [DEBUG] [TestEventLogger]       at com.cloudbees.hudson.plugins.folder.properties.FolderCredentialsProvider$FolderCredentialsProperty$DescriptorImpl.<init>(FolderCredentialsProvider.java:443)
14:19:19.071 [DEBUG] [TestEventLogger] 
14:19:19.071 [DEBUG] [TestEventLogger]     1 error
14:19:19.072 [DEBUG] [TestEventLogger]          at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
...
...
14:19:19.095 [DEBUG] [TestEventLogger]     Caused by: java.lang.NoClassDefFoundError: com/cloudbees/plugins/credentials/CredentialsProvider
14:19:19.095 [DEBUG] [TestEventLogger]          at java.lang.ClassLoader.defineClass1(Native Method)
14:19:19.096 [DEBUG] [TestEventLogger]          at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
14:19:19.096 [DEBUG] [TestEventLogger]          at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
...
...
14:19:19.106 [DEBUG] [TestEventLogger]          ... 28 more
14:19:19.106 [DEBUG] [TestEventLogger]     Caused by: java.lang.ClassNotFoundException: com.cloudbees.plugins.credentials.CredentialsProvider
14:19:19.106 [DEBUG] [TestEventLogger]          at java.net.URLClassLoader.findClass(URLClassLoader.java:381)


14:32:03.972 [DEBUG] [TestEventLogger] com.dslexample.JobScriptsSpec > test script test.groovy FAILED
14:32:03.973 [DEBUG] [TestEventLogger]     Expected no exception to be thrown, but got 'java.lang.NullPointerException'
14:32:03.973 [DEBUG] [TestEventLogger]         at spock.lang.Specification.noExceptionThrown(Specification.java:118)
14:32:03.973 [DEBUG] [TestEventLogger]         at com.dslexample.JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:45)
14:32:03.973 [DEBUG] [TestEventLogger] 
14:32:03.973 [DEBUG] [TestEventLogger]         Caused by:
14:32:03.973 [DEBUG] [TestEventLogger]         java.lang.NullPointerException
14:32:03.973 [DEBUG] [TestEventLogger]             at jenkins.branch.MultiBranchProject.init2(MultiBranchProject.java:139)
14:32:03.973 [DEBUG] [TestEventLogger]             at jenkins.branch.MultiBranchProject.onLoad(MultiBranchProject.java:123)
14:32:03.973 [DEBUG] [TestEventLogger]             at hudson.model.Items.load(Items.java:372)
14:32:03.973 [DEBUG] [TestEventLogger]             at hudson.model.ItemGroupMixIn$4.call(ItemGroupMixIn.java:276)
14:32:03.973 [DEBUG] [TestEventLogger]             at hudson.model.ItemGroupMixIn$4.call(ItemGroupMixIn.java:274)
14:32:03.973 [DEBUG] [TestEventLogger]             at hudson.model.Items.whileUpdatingByXml(Items.java:135)
14:32:03.973 [DEBUG] [TestEventLogger]             at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:274)
14:32:03.973 [DEBUG] [TestEventLogger]             at jenkins.model.Jenkins.createProjectFromXML(Jenkins.java:3821)
14:32:03.973 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.plugin.JenkinsJobManagement.createNewItem(JenkinsJobManagement.java:571)
14:32:03.973 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.plugin.JenkinsJobManagement.createOrUpdateConfig(JenkinsJobManagement.java:147)
14:32:03.973 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.dsl.AbstractDslScriptLoader.extractGeneratedJobs_closure4(AbstractDslScriptLoader.groovy:197)
14:32:03.973 [DEBUG] [TestEventLogger]             at groovy.lang.Closure.call(Closure.java:414)
14:32:03.973 [DEBUG] [TestEventLogger]             at groovy.lang.Closure.call(Closure.java:430)
14:32:03.973 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.dsl.AbstractDslScriptLoader.extractGeneratedJobs(AbstractDslScriptLoader.groovy:190)
14:32:03.973 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.dsl.AbstractDslScriptLoader.extractGeneratedItems(AbstractDslScriptLoader.groovy:177)
14:32:03.973 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts_closure1(AbstractDslScriptLoader.groovy:62)
14:32:03.973 [DEBUG] [TestEventLogger]             at groovy.lang.Closure.call(Closure.java:414)
14:32:03.973 [DEBUG] [TestEventLogger]             at groovy.lang.Closure.call(Closure.java:430)
14:32:03.974 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts(AbstractDslScriptLoader.groovy:46)
14:32:03.974 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:85)
14:32:03.974 [DEBUG] [TestEventLogger]             at com.dslexample.JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:41)
```

### Reproduce steps

1. checkout that repo
2. change versions in `gradle.properties`:
```
jobDslVersion=1.61
jenkinsVersion=2.46.2
```
3. Add plugins to test deps:

```diff
diff --git a/build.gradle b/build.gradle
index 2b0660f..eeb0631 100644
--- a/build.gradle
+++ b/build.gradle
@@ -42,11 +42,17 @@ dependencies {
     testCompile "org.jenkins-ci.plugins:job-dsl:${jobDslVersion}@jar"
     testCompile 'org.jenkins-ci.plugins:structs:1.2@jar'
     testCompile 'org.jenkins-ci.plugins:cloudbees-folder:5.0@jar'
+    testCompile 'org.jenkins-ci.plugins:git:3.0.1'
 
     // plugins to install in test instance
     testPlugins 'org.jenkins-ci.plugins:ghprb:1.31.4'
     testPlugins 'com.coravy.hudson.plugins.github:github:1.19.0'
     testPlugins 'org.jenkins-ci.plugins:cloudbees-folder:5.0'
+    testPlugins 'org.jenkins-ci.plugins.workflow:workflow-scm-step:2.3'
+    testPlugins 'org.jenkins-ci.plugins.workflow:workflow-cps:2.1'
+    testPlugins 'org.jenkins-ci.plugins.workflow:workflow-multibranch:2.3'
+    testPlugins 'org.jenkins-ci.plugins:build-pipeline-plugin:1.5.2'
+    testPlugins 'org.jenkins-ci.plugins:junit:1.18'
 
     // for the RestApiScriptRunner
     compile('org.codehaus.groovy.modules.http-builder:http-builder:0.7.2') {
```

4. Add `test.groovy` to `jobs` with such content and start tests `./gradlew clean test --debug`:

```groovy
multibranchPipelineJob('test-job') {
    branchSources {
        github {
            apiUri('https://github.com/api/v3/')
            scanCredentialsId('my-creds')
            checkoutCredentialsId('my-creds')
            repoOwner('me')
            repository('test-job')
            includes('*')
        }
    }

    orphanedItemStrategy {
        discardOldItems {
            daysToKeep(3)
        }
    }

    triggers {
        periodic(1)  // 1 minute if not otherwise built
    }
}
```

**Comment by sheehan** [comment]
It seems to work if I add:

```groovy
testPlugins 'org.jenkins-ci.plugins:github-branch-source:2.0.5'
```

**Comment by LawYard** [comment]
@sheehan 
Thx! Thats helped me! How u find that I need to add current plugin to test?

**Comment by sheehan** [comment]
No problem. When I ran the tests with `--debug` I saw a warning about missing a required plugin or something like that.
