### ISSUE TITLE
gradle test fails if DSL groovy contains `__FILE__` 

### ISSUE THREAD

**Issue by sampritavh** [sheehan/job-dsl-gradle-example#88]
Is there a way we can use `__FILE__` to get script location programmatically in DSL and still use gradle build?  
One of our DSL groovy files are using `__FILE__` as described in  https://github.com/jenkinsci/job-dsl-plugin/wiki/Job-DSL-Commands#script-location . However `./gradlew test` fails with  following error
```
javaposse.jobdsl.dsl.DslScriptException: (script, line 3) No such property: __FILE__ for class: script
17:55:34.636 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:107)
17:55:34.637 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts_closure1(AbstractDslScriptLoader.groovy:60)
17:55:34.637 [DEBUG] [TestEventLogger]             at groovy.lang.Closure.call(Closure.java:414)
17:55:34.637 [DEBUG] [TestEventLogger]             at groovy.lang.Closure.call(Closure.java:430)
17:55:34.637 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts(AbstractDslScriptLoader.groovy:46)
17:55:34.637 [DEBUG] [TestEventLogger]             at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:81)
17:55:34.637 [DEBUG] [TestEventLogger]             at com.flux7.dslfactory.JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:25)
17:55:34.637 [DEBUG] [TestEventLogger] 
17:55:34.637 [DEBUG] [TestEventLogger]             Caused by:
17:55:34.637 [DEBUG] [TestEventLogger]             groovy.lang.MissingPropertyException: No such property: __FILE__ for class: script
17:55:34.637 [DEBUG] [TestEventLogger]                 at script.run(script:3)
17:55:34.637 [DEBUG] [TestEventLogger]                 at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:124)
17:55:34.637 [DEBUG] [TestEventLogger]                 at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:101)
17:55:34.637 [DEBUG] [TestEventLogger]                 ... 6 more
```

**Comment by sheehan** [comment]
Hi @sampritavh. You should be able to bind that variable by replacing [this line](https://github.com/sheehan/job-dsl-gradle-example/blob/e818488133ce7441c9697abf675fb60f20b9d2d4/src/test/groovy/com/dslexample/JobScriptsSpec.groovy#L40):

```groovy
JobManagement jm = new JenkinsJobManagement(System.out, [:], new File('.'))
```

with this:
```groovy
JobManagement jm = new JenkinsJobManagement(System.out, [__FILE__: 'value-for-testing'], new File('.'))
```

**Comment by sampritavh** [comment]
Thank you @sheehan .This worked!.  I was able to build with this setting 
```
JobManagement jm = new JenkinsFileJobManagement(
                System.out, [ __FILE__:file.absolutePath
```
