### ISSUE TITLE
Request for better docs regarding auto-generated DSL - example?

### ISSUE THREAD

**Issue by marvinthepa** [sheehan/job-dsl-gradle-example#90]
This is what the current documentation looks like:

> Plugins providing auto-generated DSL must be added to the build dependencies

The question is: where/how do they need to be added to the build dependencies? I guess an example would make sense.

More details on my concrete problem:

I have tried adding

```
testPlugins('org.jenkins-ci.plugins.workflow:workflow-aggregator:2.5') {
        exclude module: 'ace-editor' // workaround for dependency issue
}
```

To pull in the pipeline dependencies, but it doesn't work:

```
com.dslexample.JobScriptsSpec > test script example1Jobs.groovy FAILED
    org.spockframework.runtime.UnallowedExceptionThrownError at JobScriptsSpec.groovy:47
        Caused by: javaposse.jobdsl.dsl.DslScriptException at JobScriptsSpec.groovy:43
            Caused by: groovy.lang.MissingMethodException at JobScriptsSpec.groovy:43
...
Expected no exception to be thrown, but got 'javaposse.jobdsl.dsl.DslScriptException'
	at spock.lang.Specification.noExceptionThrown(Specification.java:118)
	at com.dslexample.JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:47)
Caused by: javaposse.jobdsl.dsl.DslScriptException: (script, line 70) No signature of method: javaposse.jobdsl.dsl.helpers.properties.FolderPropertiesContext.folderLibraries() is applicable for argument types: (script$_run_closure1$_closure6$_closure7) values: [script$_run_closure1$_closure6$_closure7@5abbc22c]
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:107)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts_closure1(AbstractDslScriptLoader.groovy:60)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts(AbstractDslScriptLoader.groovy:46)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:81)
	at com.dslexample.JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:43)
Caused by: groovy.lang.MissingMethodException: No signature of method: javaposse.jobdsl.dsl.helpers.properties.FolderPropertiesContext.folderLibraries() is applicable for argument types: (script$_run_closure1$_closure6$_closure7) values: [script$_run_closure1$_closure6$_closure7@5abbc22c]
	at javaposse.jobdsl.dsl.AbstractExtensibleContext.methodMissing(AbstractExtensibleContext.groovy:19)
	at script.run_closure1$_closure6(script:70)
	at script.run_closure1$_closure6(script)
	at javaposse.jobdsl.dsl.ContextHelper.executeInContext(ContextHelper.groovy:16)
	at javaposse.jobdsl.dsl.Folder.properties(Folder.groovy:70)
	at script.run_closure1(script:69)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at javaposse.jobdsl.dsl.JobParent.processItem(JobParent.groovy:114)
	at javaposse.jobdsl.dsl.JobParent.folder(JobParent.groovy:208)
	at script.run(script:65)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:124)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:101)
	... 6 more
```

The offending code is the following:

```
folder(imagesFolder) {
    displayName('Docker Images')

    properties {
        folderLibraries {
            libraries {
                libraryConfiguration {
                    name "bla"
                    retriever {
                        ...
                    }
                }
            }
        }
    }
}
```

The code was generated using the ["Automatically Generated DSL"](https://github.com/jenkinsci/job-dsl-plugin/wiki/Automatically-Generated-DSL) and works when executing on Jenkins.

**Comment by sheehan** [comment]
Try:
```groovy
testPlugins 'org.jenkins-ci.plugins.workflow:workflow-cps-global-lib:2.7'
```

**Comment by marvinthepa** [comment]
Thanks @sheehan.

Btw. thanks a lot for this repo, it is very useful in general.

This fails resolving dependencies (which I guess is not a problem with your repo, but somewhere else):

```
Could not resolve all dependencies for configuration ':testPlugins'.
> Could not find ace-editor.jar (org.jenkins-ci.ui:ace-editor:1.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/org/jenkins-ci/ui/ace-editor/1.0.1/ace-editor-1.0.1.ja
```

using

```
    testPlugins('org.jenkins-ci.plugins.workflow:workflow-cps-global-lib:2.7') {
        exclude module: 'ace-editor'
    }
```

lead to the same exception as stated above..

**Comment by sheehan** [comment]
Thanks @marvinthepa.

I've added this to [example9](https://github.com/sheehan/job-dsl-gradle-example/blob/master/src/jobs/example9Jobs.groovy#L55) and got the test passing after making a few updates. See https://github.com/sheehan/job-dsl-gradle-example/commit/e37e9c83fdeb2a67d98a5d199027bbc92ad4c348. Let me know if that helps.

**Comment by marvinthepa** [comment]
Thanks a lot for your efforts.

Strangely enough, this still fails for me - without the exclusion I get a dependency resolution error regarding `ace-editor`, when excluding it I get `No signature of method: javaposse.jobdsl.dsl.helpers.properties.FolderPropertiesContext.folderLibraries() is applicable`...

I will check what is wrong with my local gradle settings that might be causing the dependency issue..

**Comment by marvinthepa** [comment]
Seems that I am actually being bitten by https://issues.jenkins-ci.org/browse/INFRA-900. I don't know why it works for you :-).

**Comment by marvinthepa** [comment]
This workaround for https://issues.jenkins-ci.org/browse/INFRA-900 works for me:

```groovy
repositories {
    mavenCentral()
    maven { url 'http://repo.jenkins-ci.org/releases/' }
    jcenter()
}
...
dependencies {
...
    testCompile('org.jenkins-ci.main:jenkins-test-harness:2.22') {
        exclude group: 'org.netbeans.modules', module: 'org-netbeans-insane'
    }
...
}
```

**Comment by seflue** [comment]
I have an additional question on this topic: when I use Git as Retriever like the following:

```groovy
folder(imagesFolder) {
    displayName('Docker Images')

    properties {
        folderLibraries {
            libraries {
                libraryConfiguration {
                    name "bla"
                    retriever {
                        modernSCM {
                            scm {                   
                                git {
                                    id 'my-shared-lib'
                                    remote 'git://gitserver:gitrepo'
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
I get this error:

```
Expected no exception to be thrown, but got 'javaposse.jobdsl.dsl.DslScriptException'
Expected no exception to be thrown, but got 'javaposse.jobdsl.dsl.DslScriptException'
	at spock.lang.Specification.noExceptionThrown(Specification.java:118)
	at JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:24)
Caused by: javaposse.jobdsl.dsl.DslScriptException: (Folders.groovy, line 43) No signature of method: javaposse.jobdsl.plugin.structs.DescribableListContext.git() is applicable for argument types: (de.bahntechnik.dd.jobdsl.job.helper.Folders$_addIntegrationTestFolder_closure1$_closure2$_closure3$_closure4$_closure5$_closure6$_closure7$_closure8$_closure9$_closure10) values: [de.bahntechnik.dd.jobdsl.job.helper.Folders$_addIntegrationTestFolder_closure1$_closure2$_closure3$_closure4$_closure5$_closure6$_closure7$_closure8$_closure9$_closure10@260ba97d]
Possible solutions: wait(), wait(long), is(java.lang.Object), with(groovy.lang.Closure), any(), grep()
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:107)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts_closure1(AbstractDslScriptLoader.groovy:60)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts(AbstractDslScriptLoader.groovy:46)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:81)
	at JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:21)
...
```

Is there any plugin in the dependencies, I should add?
