### ISSUE TITLE
Documentation Request About Git-Retriever For Shared Libraries In Folders

### ISSUE THREAD

**Issue by seflue** [sheehan/job-dsl-gradle-example#92]
I have an additional question on topic #90 : when I use Git as Retriever like the following:

```groovy
folder(imagesFolder) {
    displayName('Docker Images')

    properties {
        folderLibraries {
            libraries {
                libraryConfiguration {
                    name "bla"
                    retriever {
                        modernSCM {
                            scm {                   
                                git {
                                    id 'my-shared-lib'
                                    remote 'git://gitserver:gitrepo'
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
I get this error:

```
Expected no exception to be thrown, but got 'javaposse.jobdsl.dsl.DslScriptException'
Expected no exception to be thrown, but got 'javaposse.jobdsl.dsl.DslScriptException'
	at spock.lang.Specification.noExceptionThrown(Specification.java:118)
	at JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:24)
Caused by: javaposse.jobdsl.dsl.DslScriptException: (Folders.groovy, line 43) No signature of method: javaposse.jobdsl.plugin.structs.DescribableListContext.git() is applicable for argument types: (de.bahntechnik.dd.jobdsl.job.helper.Folders$_addIntegrationTestFolder_closure1$_closure2$_closure3$_closure4$_closure5$_closure6$_closure7$_closure8$_closure9$_closure10) values: [de.bahntechnik.dd.jobdsl.job.helper.Folders$_addIntegrationTestFolder_closure1$_closure2$_closure3$_closure4$_closure5$_closure6$_closure7$_closure8$_closure9$_closure10@260ba97d]
Possible solutions: wait(), wait(long), is(java.lang.Object), with(groovy.lang.Closure), any(), grep()
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:107)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts_closure1(AbstractDslScriptLoader.groovy:60)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts(AbstractDslScriptLoader.groovy:46)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:81)
	at JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:21)
...
```

Is there any plugin in the dependencies, I should add?

PS: On Jenkins of course this code works like expected.

**Comment by sheehan** [comment]
It looks like adding this will fix it:

```groovy
testPlugins 'org.jenkins-ci.plugins:git:3.7.0'
```

**Comment by marvinthepa** [comment]
@seflue:

I had the same problem, managed to work around it to comment out unneeded dependencies:

```groovy
    // plugins to install in test instance
    testPlugins 'org.jenkins-ci.plugins.workflow:workflow-aggregator:2.5'
    testPlugins 'org.jenkins-ci.plugins.workflow:workflow-cps-global-lib:2.9'
    testPlugins 'org.jenkins-ci.plugins:git:3.7.0'
//    testPlugins 'org.jenkins-ci.plugins:ghprb:1.31.4'
//    testPlugins 'com.coravy.hudson.plugins.github:github:1.19.0'
//    testPlugins 'org.jenkins-ci.plugins:cloudbees-folder:5.12'
    testPlugins 'org.jenkins-ci.plugins:credentials:2.1.10'
```

I think it is the github plugin that causes the issues, maybe it provides a method "git" somewhere that has a different signature or something.

I hope you don't need those dependencies..
